# -*- coding: utf-8 -*-
"""Project_1_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z-xAkRnwKJ38OKPbnYLKs6CDmjZAjf8r
"""

import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# ----------------------------
# 0) Load cleaned dataset
# ----------------------------
DATA_PATH = "SOTU_Data_Final.csv"
df = pd.read_csv(DATA_PATH)

# Standardize column names if needed (safe)
df.columns = [c.strip() for c in df.columns]

# Required columns
required = ["President", "Year", "Title", "Text"]
missing_required = [c for c in required if c not in df.columns]
if missing_required:
    raise ValueError(f"Missing required columns: {missing_required}. Found: {list(df.columns)}")

# Ensure Year numeric
df["Year"] = pd.to_numeric(df["Year"], errors="coerce")

# ----------------------------
# 1) Basic data validation
# ----------------------------
print("Rows:", len(df))
print("Year range:", int(df["Year"].min()), "-", int(df["Year"].max()))

print("\nMissing values by column:")
print(df.isna().sum().sort_values(ascending=False))

# Drop rows missing core fields (EDA sanity)
df = df.dropna(subset=["Year", "Text"]).copy()

# Check duplicates (same President+Year+Title)
dupe_mask = df.duplicated(subset=["President", "Year", "Title"], keep=False)
dupes = df[dupe_mask].sort_values(["Year", "President", "Title"])
print("\nPotential duplicates (President, Year, Title):", dupes.shape[0])
if len(dupes) > 0:
    print(dupes[["President", "Year", "Title"]].head(10))

# One speech per year? (Not always true historically; still useful check)
counts_per_year = df.groupby("Year").size()
print("\nYears with >1 speech in dataset (first 10):")
print(counts_per_year[counts_per_year > 1].head(10))

# ----------------------------
# 2) If needed: filter pre-1850 (your plan)
# ----------------------------
df = df[df["Year"] >= 1850].copy()

# ----------------------------
# 3) Crisis labeling (ONLY if you don't already have it)
# ----------------------------
# If you already have Is_Crisis + Crisis_Name, this block will skip automatically.
if "Is_Crisis" not in df.columns:
    # Crisis periods as (name, start_year, start_month, end_year, end_month)
    # For M2 EDA, year-level labeling is enough: we label a year as crisis if any part of the period overlaps that year.
    crisis_periods = [
        ("Panic of 1857", 1857, 6, 1858, 12),
        ("Civil War", 1861, 4, 1865, 5),
        ("Recession 1865-1867", 1865, 4, 1867, 12),
        ("Recession 1869-1870", 1869, 6, 1870, 12),
        ("Panic of 1873 / Long Depression", 1873, 10, 1879, 3),
        ("Recession 1882-1885", 1882, 3, 1885, 5),
        ("Recession 1890-1891", 1890, 7, 1891, 5),
        ("Panic of 1893", 1893, 1, 1894, 6),
        ("Panic of 1896", 1895, 12, 1897, 6),
        ("Recession 1902-1904", 1902, 9, 1904, 8),
        ("Panic of 1907", 1907, 5, 1908, 6),
        ("Panic of 1910-1911", 1910, 1, 1912, 1),
        ("Recession 1913-1914", 1913, 1, 1914, 12),
        ("WWI", 1914, 7, 1918, 11),
        ("Recession 1918-1919", 1918, 8, 1919, 3),
        ("Recession 1920-1921", 1920, 1, 1921, 7),
        ("Recession 1926-1927", 1926, 10, 1927, 11),
        ("Great Depression", 1929, 8, 1939, 12),
        ("Recession 1937-1938", 1937, 5, 1938, 6),
        ("WWII", 1939, 9, 1945, 9),
        ("Recession 1948-1949", 1948, 11, 1949, 10),
        ("Korean War", 1950, 6, 1953, 7),
        ("Recession 1953-1954", 1953, 7, 1954, 5),
        ("Vietnam War", 1955, 11, 1975, 4),
        ("Recession 1957-1958", 1957, 8, 1958, 4),
        ("Recession 1960-1961", 1960, 4, 1961, 2),
        ("Recession 1973-1975", 1973, 11, 1975, 3),
        ("Recession 1980", 1980, 1, 1980, 7),
        ("Recession 1981-1982", 1981, 7, 1982, 11),
        ("Early 90s Recession", 1990, 7, 1991, 3),
        ("Dot Com Recession", 2001, 3, 2001, 11),
        ("War on Terror / Post 9/11", 2001, 9, 2003, 5),
        ("Great Recession", 2007, 12, 2009, 6),
        ("COVID-19 Pandemic / Recession", 2020, 3, 2020, 5),
    ]

    def crisis_for_year(y: int):
        """Return (is_crisis, crisis_name) for a given year based on overlap with any crisis period."""
        names = []
        for name, sy, sm, ey, em in crisis_periods:
            if sy <= y <= ey:
                names.append(name)
        if not names:
            return 0, np.nan
        # If multiple overlap in a year, keep the first and optionally join
        return 1, "; ".join(names)

    crisis_labels = df["Year"].astype(int).apply(crisis_for_year)
    df["Is_Crisis"] = crisis_labels.apply(lambda x: x[0])
    df["Crisis_Name"] = crisis_labels.apply(lambda x: x[1])

# ----------------------------
# 4) Text feature engineering (EDA-friendly)
# ----------------------------
# Make sure Text is a string
df["Text"] = df["Text"].astype(str)

def word_count(s: str) -> int:
    return len(re.findall(r"\b\w+\b", s))

def sentence_count(s: str) -> int:
    # Simple sentence proxy: counts ., !, ?
    return len(re.findall(r"[.!?]+", s))

df["char_count"] = df["Text"].str.len()
df["word_count"] = df["Text"].apply(word_count)
df["sentence_count"] = df["Text"].apply(sentence_count)

# ----------------------------
# 5) EDA questions + outputs
# ----------------------------

# Q1: Ratio of crisis vs non-crisis
ratio = df["Is_Crisis"].value_counts(dropna=False).rename_axis("Is_Crisis").reset_index(name="n")
ratio["prop"] = ratio["n"] / ratio["n"].sum()
print("\nCrisis vs non-crisis ratio:")
print(ratio)

plt.figure()
plt.bar(ratio["Is_Crisis"].astype(str), ratio["n"])
plt.title("Count of SOTU Speeches: Crisis vs Non-Crisis")
plt.xlabel("Is_Crisis (0 = No, 1 = Yes)")
plt.ylabel("Number of Speeches")
plt.show()

# Q2: How many SOTUs are we using?
print("\nTotal speeches used in analysis (Year >= 1850):", len(df))

# Q3: Types of crises and average length
crisis_summary = (
    df[df["Is_Crisis"] == 1]
    .groupby("Crisis_Name", dropna=False)
    .agg(
        speeches=("Title", "count"),
        avg_words=("word_count", "mean"),
        median_words=("word_count", "median"),
    )
    .sort_values("speeches", ascending=False)
)
print("\nCrisis type summary (top 15):")
print(crisis_summary.head(15))

# Plot: Avg word count by crisis vs non-crisis
by_crisis = df.groupby("Is_Crisis").agg(avg_words=("word_count", "mean"), avg_sentences=("sentence_count", "mean"))
print("\nAverage length by crisis flag:")
print(by_crisis)

plt.figure()
plt.bar(by_crisis.index.astype(str), by_crisis["avg_words"])
plt.title("Average Word Count: Crisis vs Non-Crisis")
plt.xlabel("Is_Crisis")
plt.ylabel("Average Word Count")
plt.show()

# ----------------------------
# 0) Validate inputs
# ----------------------------
required_cols = {"Year", "Crisis_Name"}
missing = required_cols - set(df.columns)
if missing:
    raise ValueError(f"Missing required columns: {missing}")

df["Crisis_Name"] = df["Crisis_Name"].fillna("").astype(str)
df["Year"] = pd.to_numeric(df["Year"], errors="coerce")

# ----------------------------
# 1) Crisis-type rules
#   - Any "panic" => ECONOMIC
#   - Military keywords => MILITARY
#   - Remaining crisis labels => ECONOMIC
# ----------------------------
military_keywords = [
    "civil war", "mexican-american", "spanish-american", "philippine",
    "korean", "vietnam", "wwi", "ww1", "wwii", "ww2",
    "war on terror", "terror", "9/11", "missile", "war"
]

def classify_crisis_type(crisis_name: str) -> str:
    s = crisis_name.lower().strip()
    if not s:
        return "none"
    if "panic" in s:
        return "economic"
    if any(k in s for k in military_keywords):
        return "military"
    return "economic"   # everything else is treated as economic

df["Crisis_Type"] = df["Crisis_Name"].apply(classify_crisis_type)

# ----------------------------
# 2) Speech-level counts
# ----------------------------
speech_counts = (
    df[df["Crisis_Type"] != "none"]
    .groupby("Crisis_Type")
    .size()
    .reindex(["military", "economic"], fill_value=0)
)

print("\nSpeech-level counts by Crisis_Type:")
print(speech_counts)

# ----------------------------
# 3) Year-level counts
#   Rule: military overrides economic within the same year
# ----------------------------
def collapse_year_type(types):
    types = set(t for t in types if t != "none")
    if "military" in types:
        return "military"
    if "economic" in types:
        return "economic"
    return "none"

year_df = (
    df.dropna(subset=["Year"])
      .assign(Year=lambda d: d["Year"].astype(int))
      .groupby("Year")["Crisis_Type"]
      .apply(collapse_year_type)
      .reset_index(name="Final_Crisis_Type")
)

year_counts = (
    year_df[year_df["Final_Crisis_Type"] != "none"]
    .groupby("Final_Crisis_Type")
    .size()
    .reindex(["military", "economic"], fill_value=0)
)

print("\nYear-level counts by Crisis_Type:")
print(year_counts)

# ----------------------------
# 4) Bar plot + counts at bottom
# ----------------------------
plt.figure(figsize=(6,4))

labels = year_counts.index.tolist()
values = year_counts.values.tolist()

bars = plt.bar(labels, values)
plt.title("Crisis Years by Type")
plt.xlabel("Crisis Type")
plt.ylabel("Number of Years")

# ---- ADD COUNTS ON TOP OF BARS ----
for bar in bars:
    height = bar.get_height()
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        height + 1,              # slightly above bar
        str(int(height)),
        ha="center",
        va="bottom"
    )

plt.tight_layout()
plt.show()

# ----------------------------
# 5) Sanity check: panic => economic
# ----------------------------
panic_misclassified = df[
    df["Crisis_Name"].str.contains("panic", case=False, na=False) &
    (df["Crisis_Type"] != "economic")
]

print("\nPanic misclassified rows (should be 0):", len(panic_misclassified))

# ----------------------------
# 1) Collapse to ONE row per year
# ----------------------------
year_level = (
    df.dropna(subset=["Year"])
      .assign(Year=lambda d: d["Year"].astype(int))
      .groupby("Year")["Is_Crisis"]
      .max()   # if ANY speech in that year is crisis → year is crisis
      .reset_index()
)

# ----------------------------
# 2) Count crisis vs non-crisis YEARS
# ----------------------------
year_counts = (
    year_level["Is_Crisis"]
    .value_counts()
    .sort_index()   # 0 first, then 1
)

print("\nYear-level counts (0 = Non-Crisis, 1 = Crisis):")
print(year_counts)

# ----------------------------
# 3) Bar plot with counts on TOP
# ----------------------------
labels = ["Non-Crisis (0)", "Crisis (1)"]
values = [year_counts.get(0, 0), year_counts.get(1, 0)]

plt.figure(figsize=(6,4))
bars = plt.bar(labels, values)

plt.title("Count of SOTU Years: Crisis vs Non-Crisis")
plt.xlabel("Year Type")
plt.ylabel("Number of Years")

# Add counts on top
for bar in bars:
    height = bar.get_height()
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        height + 1,
        str(int(height)),
        ha="center",
        va="bottom"
    )

plt.tight_layout()
plt.show()

crisis_counts = df['crisis_name'].value_counts(dropna=True)

# Display the frequency table
print("Frequency Table for crisis_name:")
print(crisis_counts)

# Optional: Calculate percentages
crisis_pct = df['crisis_name'].value_counts(normalize=True, dropna=False) * 100
print("\nPercentage Distribution:")
print(crisis_pct)

# Create the bar chart
plt.figure(figsize=(12, 6))
crisis_counts.plot(kind='bar', color='skyblue', edgecolor='black')
plt.title('Frequency of Crises mentioned in SOTU Addresses')
plt.xlabel('Crisis Name')
plt.ylabel('Frequency')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()

# Save the plot
plt.savefig('crisis_frequency_chart.png')